# Generated by Django 5.2.5 on 2025-08-29 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_Departamento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cod_Ciudad', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=255)),
                ('cod_Departamento', models.ForeignKey(db_column='cod_Departamento', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('cod_lugar', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('cod_Ciudad', models.ForeignKey(db_column='cod_Ciudad', on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('cod_Mesa', models.BigAutoField(primary_key=True, serialize=False)),
                ('mesa', models.IntegerField()),
                ('cod_lugar', models.ForeignKey(db_column='cod_lugar', on_delete=django.db.models.deletion.CASCADE, to='core.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_Nombre', models.CharField(max_length=255)),
                ('segundo_Nombre', models.CharField(max_length=255)),
                ('primer_Apellido', models.CharField(max_length=255)),
                ('segundo_Apellido', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('jurado', models.CharField(max_length=50)),
                ('cod_Mesa', models.ForeignKey(db_column='cod_Mesa', on_delete=django.db.models.deletion.CASCADE, to='core.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('cod_Registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('registro', models.IntegerField()),
                ('cedula', models.ForeignKey(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
