# Generated by Django 5.2.5 on 2025-09-02 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_Departamento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cod_Ciudad', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=255)),
                ('cod_Departamento', models.ForeignKey(db_column='cod_Departamento', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('cod_lugar', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_lugar', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('cod_Ciudad', models.ForeignKey(db_column='cod_Ciudad', on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('cod_Mesa', models.BigAutoField(primary_key=True, serialize=False)),
                ('mesa', models.IntegerField()),
                ('cod_lugar', models.ForeignKey(db_column='cod_lugar', on_delete=django.db.models.deletion.CASCADE, to='core.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_Nombre', models.CharField(max_length=255)),
                ('segundo_Nombre', models.CharField(max_length=255)),
                ('primer_Apellido', models.CharField(max_length=255)),
                ('segundo_Apellido', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('jurado', models.CharField(max_length=50)),
                ('cod_Mesa', models.ForeignKey(db_column='cod_Mesa', on_delete=django.db.models.deletion.CASCADE, to='core.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('cod_Registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('registro', models.IntegerField()),
                ('cedula', models.ForeignKey(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
