# Generated by Django 5.2.5 on 2025-08-28 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('DepartamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartamentoNombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('CiudadId', models.AutoField(primary_key=True, serialize=False)),
                ('CiudadNombre', models.CharField(max_length=32)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Lugarvoto',
            fields=[
                ('LugarId', models.AutoField(primary_key=True, serialize=False)),
                ('DireccionVoto', models.CharField(max_length=32)),
                ('MesaVoto', models.IntegerField()),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PersonaId', models.AutoField(primary_key=True, serialize=False)),
                ('PersonaNombre', models.CharField(max_length=39)),
                ('PersonaApellido', models.CharField(max_length=39)),
                ('PersonaGenero', models.CharField(max_length=1)),
                ('PersonaFechaN', models.DateField()),
                ('PersonaJurado', models.BooleanField()),
                ('Lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lugarvoto')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('RegistrosId', models.AutoField(primary_key=True, serialize=False)),
                ('DocId', models.IntegerField()),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
